{% set name = "myst-nb" %}
{% set version = "0.13.0" %}

# Note: Version Pins
# This project may use ~= which can be expressed as >=, <
# Example:
# ~= 2.2 is equivalent to >= 2.2, == 2.* OR >= 2.2, < 2.3
# ~= 1.4.5 is equivalent to >= 1.4.5, == 1.4.* OR >= 1.4.5, < 1.5
# https://www.python.org/dev/peps/pep-0440/#compatible-release

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a138b4ac368b2b95b0c3a007c237cdca718f9cc665dcfba3401b1635e89e4f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >= 3.6
  run:
    - docutils >= 0.15, < 0.18
    - importlib-metadata
    - ipython
    - ipywidgets >= 7.0.0, < 8
    - jupyter-cache >= 0.4.1, < 0.5
    - jupyter-sphinx >= 0.3.2, < 0.4
    - myst-parser >= 0.15.2, < 0.16
    - nbconvert >= 5.6, < 7.0
    - nbformat >= 5.0, < 6.0
    - python >= 3.6
    - pyyaml
    - sphinx >= 3.1,< 5
    - sphinx-togglebutton >= 0.2.2, < 0.3

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.nb_glue
  commands:
   - pip check

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - mmcky
